const OUTAGE_START = "outage_start"
const OUTAGE_END = "outage_end"
const AUXILIARY_ON_RANGE_LB = "auxiliary_on_lb"
const AUXILIARY_ON_RANGE_UB = "auxiliary_on_ub"
const AUXILIARY_ON_RANGE = "auxiliary_on_range"
